# Generated by Django 5.2.1 on 2025-06-02 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('type', models.CharField(max_length=50, verbose_name='Тип кузова')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная услуга')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car', verbose_name='Автомобиль')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга автомобиля',
                'verbose_name_plural': 'Услуги автомобилей',
                'unique_together': {('car', 'service')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ManyToManyField(blank=True, through='rental.CarService', through_fields=('car', 'service'), to='rental.service', verbose_name='Дополнительные услуги'),
        ),
    ]
