# Generated by Django 5.2.1 on 2025-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, to='rental.carservice', verbose_name='Выбранные услуги'),
        ),
    ]
