# Generated by Django 5.2.3 on 2025-06-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_fix_car_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.FileField(blank=True, help_text='Загрузите скан страхового полиса', null=True, upload_to='cars/documents/', verbose_name='Страховой полис'),
        ),
        migrations.AddField(
            model_name='car',
            name='technical_passport',
            field=models.FileField(blank=True, help_text='Загрузите скан технического паспорта автомобиля', null=True, upload_to='cars/documents/', verbose_name='Технический паспорт'),
        ),
    ]
