# Generated by Django 5.2.3 on 2025-06-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_car_insurance_car_technical_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='technical_passport',
        ),
        migrations.AddField(
            model_name='car',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='car_docs/', verbose_name='Документ (техпаспорт, страховка)'),
        ),
    ]
