# Generated by Django 5.2.3 on 2025-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_remove_car_insurance_remove_car_technical_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео или дополнительный материал'),
        ),
    ]
