# Generated by Django 5.2.3 on 2025-06-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_car_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, help_text='Краткое описание фотографии', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание фотографии', verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, help_text='Использовать как основное изображение автомобиля', verbose_name='Главное фото')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать в галерее', verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в галерее', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобилей',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
