# Generated by Django 5.2.1 on 2025-06-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средняя оценка'),
        ),
        migrations.AddField(
            model_name='car',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверен модератором'),
        ),
    ]
