# Generated by Django 5.2.3 on 2025-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_add_sample_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=True, verbose_name='Проверен модератором'),
        ),
    ]
